### ISSUE TITLE
[Please help!] Why are there strange gaps between rows and rows?

### ISSUE THREAD

**Issue by Qin0821** [schrodinger/fixed-data-table-2#494]
On large screen devices, there will be gaps between the fixed number of lines

![image](https://user-images.githubusercontent.com/25655555/67264506-d4ffe280-f4dd-11e9-8e92-4e971c3d2c55.png)
![image](https://user-images.githubusercontent.com/25655555/67264573-10021600-f4de-11e9-8000-d9f9586a8e46.png)
![image](https://user-images.githubusercontent.com/25655555/67264591-1db79b80-f4de-11e9-9ede-f2d1d100bcb4.png)
The upper and lower lines did not cover the gap

## Expected Behavior
The desired result is that each cell is filled with the background color

## Current Behavior
There is no background color filled between specific lines

## Steps to Reproduce (for bugs)
1. At least eight lines for easy observation;
2. At least 27 monitors, the bigger the better;

## Context
I tried to change the background color and adjust the size of each cell, but there is no layout where the div can control this gap.

app.global.css
``` css
@import "~fixed-data-table-2/dist/fixed-data-table.css";
.public_fixedDataTableRow_main {
  background-color: unset !important;
  background-image: unset !important;
}
.public_fixedDataTable_header {
  background-color: unset !important;
  background-image: unset !important;
}
.public_fixedDataTableCell_cellContent {
  padding: 0 !important;
}
.rayDesktop-table .public_fixedDataTableCell_main {
  border-color: #d1b889 !important;
  border-width: 3px !important;
  background-color: transparent !important;
  background-image: none !important;
}
```
rank.jsx
![image](https://user-images.githubusercontent.com/25655555/67265379-27da9980-f4e0-11e9-8b09-cf3d52fe0bce.png)
rank.scss
```scss
.table {
  width: 100%;
  overflow: hidden;
  border-color: #d1b889 !important;
  border-width: 3px !important;
}
.cell {
  .horizontal {
    display: flex;
    flex-direction: row;
    flex: 1;
    justify-content: center;
    align-items: center;
  }
}
.cellName {
  background-color: #C3E0C1;
}
.headerText {
  font-size: 18px;
  font-weight: bold;
  color: #8B5212;
}
```

## Your Environment
* Version used:
* Browser Name and version:1.0.0
* Operating System and version (desktop or mobile):electron macOS 10.15
